package com.ninetwozero.bf4intel.json.battlefeed;

public enum EventType {
    STATUS_MESSAGE,
    BECAME_FRIENDS,
    CREATED_FORUM_THREAD,
    WROTE_FORUM_POST,
    RECEIVED_WALL_POST,
    ADDED_FAV_SERVER,
    LEVEL_COMPLETE,
    GAME_REPORT,
    COMMENTED_GAME_REPORT,
    COMMENTED_BLOG,
    GAME_ACCESS,
    SHARED_GAME_EVENT,
    BATTLE_PACK,
    UNKNOWN
}