package com.ninetwozero.bf4intel.resources.maps.ranks;

import com.ninetwozero.bf4intel.R;

import java.util.HashMap;
import java.util.Map;

public class RankStringMap {
    private static final Map<String, Integer> map = new HashMap<String, Integer>() {
        {
            put("WARSAW_ID_P_RANK00_NAME", R.string.rank0);
            put("WARSAW_ID_P_RANK01_NAME", R.string.rank1);
            put("WARSAW_ID_P_RANK02_NAME", R.string.rank2);
            put("WARSAW_ID_P_RANK03_NAME", R.string.rank3);
            put("WARSAW_ID_P_RANK04_NAME", R.string.rank4);
            put("WARSAW_ID_P_RANK05_NAME", R.string.rank5);
            put("WARSAW_ID_P_RANK06_NAME", R.string.rank6);
            put("WARSAW_ID_P_RANK07_NAME", R.string.rank7);
            put("WARSAW_ID_P_RANK08_NAME", R.string.rank8);
            put("WARSAW_ID_P_RANK09_NAME", R.string.rank9);
            put("WARSAW_ID_P_RANK10_NAME", R.string.rank10);
            put("WARSAW_ID_P_RANK11_NAME", R.string.rank11);
            put("WARSAW_ID_P_RANK12_NAME", R.string.rank12);
            put("WARSAW_ID_P_RANK13_NAME", R.string.rank13);
            put("WARSAW_ID_P_RANK14_NAME", R.string.rank14);
            put("WARSAW_ID_P_RANK15_NAME", R.string.rank15);
            put("WARSAW_ID_P_RANK16_NAME", R.string.rank16);
            put("WARSAW_ID_P_RANK17_NAME", R.string.rank17);
            put("WARSAW_ID_P_RANK18_NAME", R.string.rank18);
            put("WARSAW_ID_P_RANK19_NAME", R.string.rank19);
            put("WARSAW_ID_P_RANK20_NAME", R.string.rank20);
            put("WARSAW_ID_P_RANK21_NAME", R.string.rank21);
            put("WARSAW_ID_P_RANK22_NAME", R.string.rank22);
            put("WARSAW_ID_P_RANK23_NAME", R.string.rank23);
            put("WARSAW_ID_P_RANK24_NAME", R.string.rank24);
            put("WARSAW_ID_P_RANK25_NAME", R.string.rank25);
            put("WARSAW_ID_P_RANK26_NAME", R.string.rank26);
            put("WARSAW_ID_P_RANK27_NAME", R.string.rank27);
            put("WARSAW_ID_P_RANK28_NAME", R.string.rank28);
            put("WARSAW_ID_P_RANK29_NAME", R.string.rank29);
            put("WARSAW_ID_P_RANK30_NAME", R.string.rank30);
            put("WARSAW_ID_P_RANK31_NAME", R.string.rank31);
            put("WARSAW_ID_P_RANK32_NAME", R.string.rank32);
            put("WARSAW_ID_P_RANK33_NAME", R.string.rank33);
            put("WARSAW_ID_P_RANK34_NAME", R.string.rank34);
            put("WARSAW_ID_P_RANK35_NAME", R.string.rank35);
            put("WARSAW_ID_P_RANK36_NAME", R.string.rank36);
            put("WARSAW_ID_P_RANK37_NAME", R.string.rank37);
            put("WARSAW_ID_P_RANK38_NAME", R.string.rank38);
            put("WARSAW_ID_P_RANK39_NAME", R.string.rank39);
            put("WARSAW_ID_P_RANK40_NAME", R.string.rank40);
            put("WARSAW_ID_P_RANK41_NAME", R.string.rank41);
            put("WARSAW_ID_P_RANK42_NAME", R.string.rank42);
            put("WARSAW_ID_P_RANK43_NAME", R.string.rank43);
            put("WARSAW_ID_P_RANK44_NAME", R.string.rank44);
            put("WARSAW_ID_P_RANK45_NAME", R.string.rank45);
            put("WARSAW_ID_P_RANK46_NAME", R.string.rank46);
            put("WARSAW_ID_P_RANK47_NAME", R.string.rank47);
            put("WARSAW_ID_P_RANK48_NAME", R.string.rank48);
            put("WARSAW_ID_P_RANK49_NAME", R.string.rank49);
            put("WARSAW_ID_P_RANK50_NAME", R.string.rank50);
            put("WARSAW_ID_P_RANK51_NAME", R.string.rank51);
            put("WARSAW_ID_P_RANK52_NAME", R.string.rank52);
            put("WARSAW_ID_P_RANK53_NAME", R.string.rank53);
            put("WARSAW_ID_P_RANK54_NAME", R.string.rank54);
            put("WARSAW_ID_P_RANK55_NAME", R.string.rank55);
            put("WARSAW_ID_P_RANK56_NAME", R.string.rank56);
            put("WARSAW_ID_P_RANK57_NAME", R.string.rank57);
            put("WARSAW_ID_P_RANK58_NAME", R.string.rank58);
            put("WARSAW_ID_P_RANK59_NAME", R.string.rank59);
            put("WARSAW_ID_P_RANK60_NAME", R.string.rank60);
            put("WARSAW_ID_P_RANK61_NAME", R.string.rank61);
            put("WARSAW_ID_P_RANK62_NAME", R.string.rank62);
            put("WARSAW_ID_P_RANK63_NAME", R.string.rank63);
            put("WARSAW_ID_P_RANK64_NAME", R.string.rank64);
            put("WARSAW_ID_P_RANK65_NAME", R.string.rank65);
            put("WARSAW_ID_P_RANK66_NAME", R.string.rank66);
            put("WARSAW_ID_P_RANK67_NAME", R.string.rank67);
            put("WARSAW_ID_P_RANK68_NAME", R.string.rank68);
            put("WARSAW_ID_P_RANK69_NAME", R.string.rank69);
            put("WARSAW_ID_P_RANK70_NAME", R.string.rank70);
            put("WARSAW_ID_P_RANK71_NAME", R.string.rank71);
            put("WARSAW_ID_P_RANK72_NAME", R.string.rank72);
            put("WARSAW_ID_P_RANK73_NAME", R.string.rank73);
            put("WARSAW_ID_P_RANK74_NAME", R.string.rank74);
            put("WARSAW_ID_P_RANK75_NAME", R.string.rank75);
            put("WARSAW_ID_P_RANK76_NAME", R.string.rank76);
            put("WARSAW_ID_P_RANK77_NAME", R.string.rank77);
            put("WARSAW_ID_P_RANK78_NAME", R.string.rank78);
            put("WARSAW_ID_P_RANK79_NAME", R.string.rank79);
            put("WARSAW_ID_P_RANK80_NAME", R.string.rank80);
            put("WARSAW_ID_P_RANK81_NAME", R.string.rank81);
            put("WARSAW_ID_P_RANK82_NAME", R.string.rank82);
            put("WARSAW_ID_P_RANK83_NAME", R.string.rank83);
            put("WARSAW_ID_P_RANK84_NAME", R.string.rank84);
            put("WARSAW_ID_P_RANK85_NAME", R.string.rank85);
            put("WARSAW_ID_P_RANK86_NAME", R.string.rank86);
            put("WARSAW_ID_P_RANK87_NAME", R.string.rank87);
            put("WARSAW_ID_P_RANK88_NAME", R.string.rank88);
            put("WARSAW_ID_P_RANK89_NAME", R.string.rank89);
            put("WARSAW_ID_P_RANK90_NAME", R.string.rank90);
            put("WARSAW_ID_P_RANK91_NAME", R.string.rank91);
            put("WARSAW_ID_P_RANK92_NAME", R.string.rank92);
            put("WARSAW_ID_P_RANK93_NAME", R.string.rank93);
            put("WARSAW_ID_P_RANK94_NAME", R.string.rank94);
            put("WARSAW_ID_P_RANK95_NAME", R.string.rank95);
            put("WARSAW_ID_P_RANK96_NAME", R.string.rank96);
            put("WARSAW_ID_P_RANK97_NAME", R.string.rank97);
            put("WARSAW_ID_P_RANK98_NAME", R.string.rank98);
            put("WARSAW_ID_P_RANK99_NAME", R.string.rank99);
            put("WARSAW_ID_P_RANK100_NAME", R.string.rank100);
            put("WARSAW_ID_P_XP1_RANK101_NAME", R.string.xp1_rank101_name);
            put("WARSAW_ID_P_XP1_RANK102_NAME", R.string.xp1_rank102_name);
            put("WARSAW_ID_P_XP1_RANK103_NAME", R.string.xp1_rank103_name);
            put("WARSAW_ID_P_XP1_RANK104_NAME", R.string.xp1_rank104_name);
            put("WARSAW_ID_P_XP1_RANK105_NAME", R.string.xp1_rank105_name);
            put("WARSAW_ID_P_XP1_RANK106_NAME", R.string.xp1_rank106_name);
            put("WARSAW_ID_P_XP1_RANK107_NAME", R.string.xp1_rank107_name);
            put("WARSAW_ID_P_XP1_RANK108_NAME", R.string.xp1_rank108_name);
            put("WARSAW_ID_P_XP1_RANK109_NAME", R.string.xp1_rank109_name);
            put("WARSAW_ID_P_XP1_RANK110_NAME", R.string.xp1_rank110_name);
            put("WARSAW_ID_P_RANK111_NAME", R.string.rank111_name);
            put("WARSAW_ID_P_RANK112_NAME", R.string.rank112_name);
            put("WARSAW_ID_P_RANK113_NAME", R.string.rank113_name);
            put("WARSAW_ID_P_RANK114_NAME", R.string.rank114_name);
            put("WARSAW_ID_P_RANK115_NAME", R.string.rank115_name);
            put("WARSAW_ID_P_RANK116_NAME", R.string.rank116_name);
            put("WARSAW_ID_P_RANK117_NAME", R.string.rank117_name);
            put("WARSAW_ID_P_RANK118_NAME", R.string.rank118_name);
            put("WARSAW_ID_P_RANK119_NAME", R.string.rank119_name);
            put("WARSAW_ID_P_RANK120_NAME", R.string.rank120_name);
        }
    };

    public static int get(final String key) {
        return map.containsKey(key)? map.get(key) : R.string.unknown;
    }
}