package com.ninetwozero.bf4intel.resources.maps.weapons;

import com.ninetwozero.bf4intel.R;

import java.util.HashMap;
import java.util.Map;

/* Contains both WNAME and INAME */

public class WeaponStringMap {
    private static final Map<String, Integer> map = new HashMap<String, Integer>() {
        {
            put("WARSAW_ID_P_SP_WNAME_USAS12NV", R.string.weapon_name_usas12nv);
            put("WARSAW_ID_P_WNAME_870", R.string.weapon_name_870);
            put("WARSAW_ID_P_WNAME_93R", R.string.weapon_name_93r);
            put("WARSAW_ID_P_WNAME_A91", R.string.weapon_name_a91);
            put("WARSAW_ID_P_WNAME_ACR", R.string.weapon_name_acr);
            put("WARSAW_ID_P_WNAME_AEK971", R.string.weapon_name_aek971);
            put("WARSAW_ID_P_WNAME_AK12", R.string.weapon_name_ak12);
            put("WARSAW_ID_P_WNAME_AK5C", R.string.weapon_name_ak5c);
            put("WARSAW_ID_P_WNAME_AKU12", R.string.weapon_name_aku12);
            put("WARSAW_ID_P_WNAME_AMR2", R.string.weapon_name_amr2);
            put("WARSAW_ID_P_WNAME_AMR2CQB", R.string.weapon_name_amr2cqb);
            put("WARSAW_ID_P_WNAME_AMR2MID", R.string.weapon_name_amr2mid);
            put("WARSAW_ID_P_WNAME_CBJMS", R.string.weapon_name_cbjms);
            put("WARSAW_ID_P_WNAME_CSLR4", R.string.weapon_name_cslr4);
            put("WARSAW_ID_P_WNAME_CZ75", R.string.weapon_name_cz75);
            put("WARSAW_ID_P_WNAME_CZ805", R.string.weapon_name_cz805);
            put("WARSAW_ID_P_WNAME_DBV12", R.string.weapon_name_dbv12);
            put("WARSAW_ID_P_WNAME_FAMAS", R.string.weapon_name_famas);
            put("WARSAW_ID_P_WNAME_FN57", R.string.weapon_name_fn57);
            put("WARSAW_ID_P_WNAME_FYJS", R.string.weapon_name_fyjs);
            put("WARSAW_ID_P_WNAME_G36C", R.string.weapon_name_g36c);
            put("WARSAW_ID_P_WNAME_GALIL21", R.string.weapon_name_galil21);
            put("WARSAW_ID_P_WNAME_GALIL23", R.string.weapon_name_galil23);
            put("WARSAW_ID_P_WNAME_GALIL52", R.string.weapon_name_galil52);
            put("WARSAW_ID_P_WNAME_GALIL53", R.string.weapon_name_galil53);
            put("WARSAW_ID_P_WNAME_GLOCK18", R.string.weapon_name_glock18);
            put("WARSAW_ID_P_WNAME_HAWK", R.string.weapon_name_hawk);
            put("WARSAW_ID_P_WNAME_HK45C", R.string.weapon_name_hk45c);
            put("WARSAW_ID_P_WNAME_JNG90", R.string.weapon_name_jng90);
            put("WARSAW_ID_P_WNAME_JS2", R.string.weapon_name_js2);
            put("WARSAW_ID_P_WNAME_LSAT", R.string.weapon_name_lsat);
            put("WARSAW_ID_P_WNAME_M1014", R.string.weapon_name_m1014);
            put("WARSAW_ID_P_WNAME_M16A4", R.string.weapon_name_m16a4);
            put("WARSAW_ID_P_WNAME_M1911", R.string.weapon_name_m1911);
            put("WARSAW_ID_P_WNAME_M200", R.string.weapon_name_m200);
            put("WARSAW_ID_P_WNAME_M240", R.string.weapon_name_m240);
            put("WARSAW_ID_P_WNAME_M249", R.string.weapon_name_m249);
            put("WARSAW_ID_P_WNAME_M39", R.string.weapon_name_m39);
            put("WARSAW_ID_P_WNAME_M40A5", R.string.weapon_name_m40a5);
            put("WARSAW_ID_P_WNAME_M412REX", R.string.weapon_name_m412rex);
            put("WARSAW_ID_P_WNAME_M416", R.string.weapon_name_m416);
            put("WARSAW_ID_P_WNAME_M4A1", R.string.weapon_name_m4a1);
            put("WARSAW_ID_P_WNAME_M82A3", R.string.weapon_name_m82a3);
            put("WARSAW_ID_P_WNAME_M82A3CQB", R.string.weapon_name_m82a3cqb);
            put("WARSAW_ID_P_WNAME_M82A3MID", R.string.weapon_name_m82a3mid);
            put("WARSAW_ID_P_WNAME_M9", R.string.weapon_name_m9);
            put("WARSAW_ID_P_WNAME_M98B", R.string.weapon_name_m98b);
            put("WARSAW_ID_P_WNAME_MG4", R.string.weapon_name_mg4);
            put("WARSAW_ID_P_WNAME_MK11", R.string.weapon_name_mk11);
            put("WARSAW_ID_P_WNAME_MP443", R.string.weapon_name_mp443);
            put("WARSAW_ID_P_WNAME_MX4", R.string.weapon_name_mx4);
            put("WARSAW_ID_P_WNAME_P226", R.string.weapon_name_p226);
            put("WARSAW_ID_P_WNAME_P90", R.string.weapon_name_p90);
            put("WARSAW_ID_P_WNAME_PDR", R.string.weapon_name_pdr);
            put("WARSAW_ID_P_WNAME_PECHENEG", R.string.weapon_name_pecheneg);
            put("WARSAW_ID_P_WNAME_PP2000", R.string.weapon_name_pp2000);
            put("WARSAW_ID_P_WNAME_QBB95", R.string.weapon_name_qbb95);
            put("WARSAW_ID_P_WNAME_QBS09", R.string.weapon_name_qbs09);
            put("WARSAW_ID_P_WNAME_QBU88", R.string.weapon_name_qbu88);
            put("WARSAW_ID_P_WNAME_QBZ951", R.string.weapon_name_qbz951);
            put("WARSAW_ID_P_WNAME_QSZ92", R.string.weapon_name_qsz92);
            put("WARSAW_ID_P_WNAME_RFBTARGET", R.string.weapon_name_rfbtarget);
            put("WARSAW_ID_P_WNAME_RPK12", R.string.weapon_name_rpk12);
            put("WARSAW_ID_P_WNAME_SAIGA12", R.string.weapon_name_saiga12);
            put("WARSAW_ID_P_WNAME_SAR21", R.string.weapon_name_sar21);
            put("WARSAW_ID_P_WNAME_SCARH", R.string.weapon_name_scarh);
            put("WARSAW_ID_P_WNAME_SCARHSV", R.string.weapon_name_scarhsv);
            put("WARSAW_ID_P_WNAME_SCORP", R.string.weapon_name_scorp);
            put("WARSAW_ID_P_WNAME_SCOUTELIT", R.string.weapon_name_scoutelit);
            put("WARSAW_ID_P_WNAME_SG553", R.string.weapon_name_sg553);
            put("WARSAW_ID_P_WNAME_SHORTY", R.string.weapon_name_shorty);
            put("WARSAW_ID_P_WNAME_SKS", R.string.weapon_name_sks);
            put("WARSAW_ID_P_WNAME_SPAS12", R.string.weapon_name_spas12);
            put("WARSAW_ID_P_WNAME_SRS", R.string.weapon_name_srs);
            put("WARSAW_ID_P_WNAME_STEYRAUG", R.string.weapon_name_steyraug);
            put("WARSAW_ID_P_WNAME_SV98", R.string.weapon_name_sv98);
            put("WARSAW_ID_P_WNAME_SVD12", R.string.weapon_name_svd12);
            put("WARSAW_ID_P_WNAME_TAURUS44", R.string.weapon_name_taurus44);
            put("WARSAW_ID_P_WNAME_TYPE88", R.string.weapon_name_type88);
            put("WARSAW_ID_P_WNAME_TYPE95B1", R.string.weapon_name_type95b1);
            put("WARSAW_ID_P_WNAME_ULTIM", R.string.weapon_name_ultim);
            put("WARSAW_ID_P_WNAME_UMP45", R.string.weapon_name_ump45);
            put("WARSAW_ID_P_WNAME_UMP9", R.string.weapon_name_ump9);
            put("WARSAW_ID_P_WNAME_USAS12", R.string.weapon_name_usas12);
            put("WARSAW_ID_P_WNAME_UTAS", R.string.weapon_name_utas);
            put("WARSAW_ID_P_XP0_WNAME_ASVAL", R.string.weapon_xp0_name_asval);
            put("WARSAW_ID_P_XP0_WNAME_DAO12", R.string.weapon_xp0_name_dao12);
            put("WARSAW_ID_P_XP0_WNAME_F2000", R.string.weapon_xp0_name_f2000);
            put("WARSAW_ID_P_XP0_WNAME_GOL", R.string.weapon_xp0_name_gol);
            put("WARSAW_ID_P_XP0_WNAME_M60E4", R.string.weapon_xp0_name_m60e4);
            put("WARSAW_ID_P_XP1_WNAME_L85A2", R.string.weapon_xp1_name_l85a2);
            put("WARSAW_ID_P_XP1_WNAME_L96A1", R.string.weapon_xp1_name_l96a1);
            put("WARSAW_ID_P_XP1_WNAME_MP7", R.string.weapon_xp1_name_mp7);
            put("WARSAW_ID_P_XP1_WNAME_MTAR21", R.string.weapon_xp1_name_mtar21);
            put("WARSAW_ID_P_XP1_WNAME_RPK74", R.string.weapon_xp1_name_rpk74);
            put("WARSAW_ID_P_INAME_40MM", R.string.weapon_iname_40mm);
            put("WARSAW_ID_P_INAME_40MM_FLASH", R.string.weapon_iname_40mm_flash);
            put("WARSAW_ID_P_INAME_40MM_LVG", R.string.weapon_iname_40mm_lvg);
            put("WARSAW_ID_P_INAME_40MM_SHG", R.string.weapon_iname_40mm_shg);
            put("WARSAW_ID_P_INAME_40MM_SMK", R.string.weapon_iname_40mm_smk);
            put("WARSAW_ID_P_INAME_ACB90", R.string.weapon_iname_acb90);
            put("WARSAW_ID_P_INAME_AMMO", R.string.weapon_iname_ammo);
            put("WARSAW_ID_P_INAME_AMMO_PACK", R.string.weapon_iname_ammo_pack);
            put("WARSAW_ID_P_INAME_ANTITANK", R.string.weapon_iname_antitank);
            put("WARSAW_ID_P_INAME_BAYONETT", R.string.weapon_iname_bayonett);
            put("WARSAW_ID_P_INAME_BEACON", R.string.weapon_iname_beacon);
            put("WARSAW_ID_P_INAME_BPKNIFE2", R.string.weapon_iname_bpknife2);
            put("WARSAW_ID_P_INAME_BPKNIFE3", R.string.weapon_iname_bpknife3);
            put("WARSAW_ID_P_INAME_BPKNIFE4", R.string.weapon_iname_bpknife4);
            put("WARSAW_ID_P_INAME_BPKNIFE5", R.string.weapon_iname_bpknife5);
            put("WARSAW_ID_P_INAME_BPKNIFE6", R.string.weapon_iname_bpknife6);
            put("WARSAW_ID_P_INAME_BPKNIFE7", R.string.weapon_iname_bpknife7);
            put("WARSAW_ID_P_INAME_BPKNIFE8", R.string.weapon_iname_bpknife8);
            put("WARSAW_ID_P_INAME_C4", R.string.weapon_iname_c4);
            put("WARSAW_ID_P_INAME_CARBINES", R.string.weapon_iname_carbines);
            put("WARSAW_ID_P_INAME_CLAYMORE", R.string.weapon_iname_claymore);
            put("WARSAW_ID_P_INAME_COMBATMEDIC", R.string.weapon_iname_combatmedic);
            put("WARSAW_ID_P_INAME_DEFIB", R.string.weapon_iname_defib);
            put("WARSAW_ID_P_INAME_DMRS", R.string.weapon_iname_dmrs);
            put("WARSAW_ID_P_INAME_EOD", R.string.weapon_iname_eod);
            put("WARSAW_ID_P_INAME_FGM148", R.string.weapon_iname_fgm148);
            put("WARSAW_ID_P_INAME_FIM92", R.string.weapon_iname_fim92);
            put("WARSAW_ID_P_INAME_FIRST_AID_PACK", R.string.weapon_iname_first_aid_pack);
            put("WARSAW_ID_P_INAME_FLARE", R.string.weapon_iname_flare);
            put("WARSAW_ID_P_INAME_FLASHBANG", R.string.weapon_iname_flashbang);
            put("WARSAW_ID_P_INAME_GRENADIER", R.string.weapon_iname_grenadier);
            put("WARSAW_ID_P_INAME_IGLA", R.string.weapon_iname_igla);
            put("WARSAW_ID_P_INAME_IMPACT", R.string.weapon_iname_impact);
            put("WARSAW_ID_P_INAME_INDIRECTFIRE", R.string.weapon_iname_indirectfire);
            put("WARSAW_ID_P_INAME_M136", R.string.weapon_iname_m136);
            put("WARSAW_ID_P_INAME_M15", R.string.weapon_iname_m15);
            put("WARSAW_ID_P_INAME_M18", R.string.weapon_iname_m18);
            put("WARSAW_ID_P_INAME_M2", R.string.weapon_iname_m2);
            put("WARSAW_ID_P_INAME_M26_FLECHETTE", R.string.weapon_iname_m26_flechette);
            put("WARSAW_ID_P_INAME_M26_FRAG", R.string.weapon_iname_m26_frag);
            put("WARSAW_ID_P_INAME_M26_MASS", R.string.weapon_iname_m26_mass);
            put("WARSAW_ID_P_INAME_M26_SLUG", R.string.weapon_iname_m26_slug);
            put("WARSAW_ID_P_INAME_M32MGL", R.string.weapon_iname_m32mgl);
            put("WARSAW_ID_P_INAME_M34", R.string.weapon_iname_m34);
            put("WARSAW_ID_P_INAME_M67", R.string.weapon_iname_m67);
            put("WARSAW_ID_P_INAME_MACHETE", R.string.weapon_iname_machete);
            put("WARSAW_ID_P_INAME_MAV", R.string.weapon_iname_mav);
            put("WARSAW_ID_P_INAME_MBTLAW", R.string.weapon_iname_mbtlaw);
            put("WARSAW_ID_P_INAME_MECHANIC", R.string.weapon_iname_mechanic);
            put("WARSAW_ID_P_INAME_MEDICBAG", R.string.weapon_iname_medicbag);
            put("WARSAW_ID_P_INAME_MORTAR", R.string.weapon_iname_mortar);
            put("WARSAW_ID_P_INAME_MOTION_SENSOR", R.string.weapon_iname_motion_sensor);
            put("WARSAW_ID_P_INAME_MPAPS", R.string.weapon_iname_mpaps);
            put("WARSAW_ID_P_INAME_NOGADGET1", R.string.weapon_iname_nogadget1);
            put("WARSAW_ID_P_INAME_NOGADGET2", R.string.weapon_iname_nogadget2);
            put("WARSAW_ID_P_INAME_PERIMETERDEFENSE", R.string.weapon_iname_perimeterdefense);
            put("WARSAW_ID_P_INAME_PLD", R.string.weapon_iname_pld);
            put("WARSAW_ID_P_INAME_REPAIR", R.string.weapon_iname_repair);
            put("WARSAW_ID_P_INAME_RPG7", R.string.weapon_iname_rpg7);
            put("WARSAW_ID_P_INAME_SHADOW", R.string.weapon_iname_shadow);
            put("WARSAW_ID_P_INAME_SHANK", R.string.weapon_iname_shank);
            put("WARSAW_ID_P_INAME_SHAREDDEFENSIVE", R.string.weapon_iname_shareddefensive);
            put("WARSAW_ID_P_INAME_SHAREDOFFENSIVE", R.string.weapon_iname_sharedoffensive);
            put("WARSAW_ID_P_INAME_SHOTGUNS", R.string.weapon_iname_shotguns);
            put("WARSAW_ID_P_INAME_SMAW", R.string.weapon_iname_smaw);
            put("WARSAW_ID_P_INAME_SNIPER", R.string.weapon_iname_sniper);
            put("WARSAW_ID_P_INAME_SOFLAM", R.string.weapon_iname_soflam);
            put("WARSAW_ID_P_INAME_SPECOPS", R.string.weapon_iname_specops);
            put("WARSAW_ID_P_INAME_SRAW", R.string.weapon_iname_sraw);
            put("WARSAW_ID_P_INAME_STARSTREAK", R.string.weapon_iname_starstreak);
            put("WARSAW_ID_P_INAME_UGS", R.string.weapon_iname_ugs);
            put("WARSAW_ID_P_INAME_V40", R.string.weapon_iname_v40);
            put("WARSAW_ID_P_INAME_XM25", R.string.weapon_iname_xm25);
            put("WARSAW_ID_P_INAME_XM25_FLECHETTE", R.string.weapon_iname_xm25_flechette);
            put("WARSAW_ID_P_INAME_XM25_SMK", R.string.weapon_iname_xm25_smk);
            put("WARSAW_ID_P_XP4_INAME_KNIFEWEAVER", R.string.weapon_knife_weaver);
            /*SECOND ASSAULT*/
            put("WARSAW_ID_P_XP0_WNAME_DAO12", R.string.weapon_dao12_fancy);
            put("WARSAW_ID_P_INAME_BPKNIFE1", R.string.weapon_knife_improvised_fancy);
            put("WARSAW_ID_P_INAME_BPKNIFE8", R.string.weapon_knife_sealknife_fancy);
            put("WARSAW_ID_P_XP0_WNAME_GOL", R.string.weapon_gol_fancy);
            put("WARSAW_ID_P_XP0_WNAME_F2000", R.string.weapon_f2000_fancy);
            put("WARSAW_ID_P_XP0_WNAME_M60E4", R.string.weapon_m60e4_fancy);
            put("WARSAW_ID_P_XP0_WNAME_ASVAL", R.string.weapon_asval_fancy);
            put("WARSAW_ID_P_INAME_BPKNIFE7", R.string.weapon_knife_bootknife_fancy);
            put("WARSAW_ID_P_XP1_VNAME_UCAV", R.string.vehicle_xp1_name_ucav);
            
            /*NAVAL STRIKE*/
            put("WARSAW_ID_P_XP2_WNAME_SR2", R.string.weapon_sr2);
            put("WARSAW_ID_P_XP2_WNAME_AR160", R.string.weapon_ar160);
            put("WARSAW_ID_P_XP2_WNAME_AWS", R.string.weapon_aws);
            put("WARSAW_ID_P_XP2_WNAME_SR338", R.string.weapon_sr338);
            put("WARSAW_ID_P_XP2_INAME_AAMINE", R.string.weapon_aamine);
            put("WARSAW_ID_P_INAME_DIVERKNIFE", R.string.weapon_knife_diver);
            put("WARSAW_ID_P_INAME_KNIFE14100BT", R.string.weapon_knife_tactical2);
            put("WARSAW_ID_P_XP2_INAME_40MM_3GL", R.string.weapon_40mm_3gl);
            put("WARSAW_ID_P_XP2_WNAME_SW40", R.string.weapon_sw40);
            put("WARSAW_ID_P_INAME_KNIFE2142", R.string.weapon_knife_2142);
            put("WARSAW_ID_P_INAME_KNIFEPRECISION", R.string.weapon_knife_precision);

            /*DRAGON'S TEETH*/
            put("WARSAW_ID_P_XP3_WNAME_UN6", R.string.weapon_un6);
            put("WARSAW_ID_P_XP3_WNAME_MPX", R.string.weapon_mpx);
            put("WARSAW_ID_P_XP3_WNAME_DEAGLE", R.string.weapon_deagle);
            put("WARSAW_ID_P_INAME_NECKKNIFE", R.string.weapon_neckknife);
            put("WARSAW_ID_P_XP3_WNAME_BULLDOG", R.string.weapon_bulldog);
            put("WARSAW_ID_P_XP3_WNAME_CS5", R.string.weapon_cs5);
            put("WARSAW_ID_P_XP3_WNAME_SHIELD", R.string.weapon_shield);

            /*FINAL STAND*/
            put("WARSAW_ID_P_XP4_WNAME_RAILGUN", R.string.weapon_railgun);
            put("WARSAW_ID_P_XP4_INAME_KNIFETANTO", R.string.weapon_knife_tanto);
            put("WARSAW_ID_P_XP4_INAME_KNIFEBIPOD", R.string.weapon_knife_c100);
            put("WARSAW_ID_P_XP4_WNAME_SPYDER", R.string.weapon_spyder);

            put("WARSAW_ID_P_WNAME_SADDLEGUN", R.string.weapon_saddlegun);
            put("WARSAW_ID_P_WNAME_L86A1", R.string.weapon_l86a2);
            put("WARSAW_ID_P_WNAME_AN94",R.string.weapon_an94);
            put("WARSAW_ID_P_WNAME_GROZA1",R.string.weapon_groza1);
            put("WARSAW_ID_P_WNAME_GROZA4",R.string.weapon_groza4);

            put("WARSAW_ID_P_XP6_INAME_M60ULT", R.string.weapon_m60ult);
        }
    };

    public static int get(final String key) {
        return map.containsKey(key)? map.get(key) : R.string.na;
    }
}