package com.ninetwozero.bf4intel.resources.maps.camoflagues;

import com.ninetwozero.bf4intel.R;

import java.util.HashMap;
import java.util.Map;

public class CamoImageMap {
    private static final Map<String, Integer> map = new HashMap<String, Integer>() {
        {
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_ADAPTIVE", R.drawable.camo_atomic_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_AUTUMN", R.drawable.camo_atomic_autumn);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_DESERT", R.drawable.camo_atomic_desert);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_NAVAL", R.drawable.camo_atomic_naval);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_SNOW", R.drawable.camo_atomic_snow);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_URBAN", R.drawable.camo_atomic_urban);
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_WOODLAND", R.drawable.camo_atomic_woodland);
            put("WARSAW_ID_P_CAMO_NAME_BEO_GAM", R.drawable.camo_beo_gam);
            put("WARSAW_ID_P_CAMO_NAME_BLACK_SHARK", R.drawable.camo_black_shark);
            put("WARSAW_ID_P_CAMO_NAME_BLUESKY", R.drawable.camo_blue_sky);
            put("WARSAW_ID_P_CAMO_NAME_BLUE_TIGER", R.drawable.camo_blue_tiger);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO1CH", R.drawable.camo_urban_airborne);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO1RU", R.drawable.camo_izlom);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO1US", R.drawable.camo_tricolor_desert);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO2CH", R.drawable.camo_dense_urban);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO2RU", R.drawable.camo_berezka);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO2US", R.drawable.camo_marpat_desert);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO3CH", R.drawable.camo_oceanic_green);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO3RU", R.drawable.camo_partizan);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO3US", R.drawable.camo_chocolate_chip);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO4CH", R.drawable.camo_pla_desert);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO4RU", R.drawable.camo_vdv_flectar);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO4US", R.drawable.camo_vine_leaf);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO5CH", R.drawable.camo_pla_naval);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO5RU", R.drawable.camo_spetsnaz_jungle);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO5US", R.drawable.camo_ucp);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO6CH", R.drawable.camo_pla_temperate);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO6RU", R.drawable.camo_rastr);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO6US", R.drawable.camo_marpat);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO7CH", R.drawable.camo_oceanic_blue);
            put("WARSAW_ID_P_CAMO_NAME_CAMO7RU", R.drawable.camo_klmk);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO7US", R.drawable.camo_tiger_stripe);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO8CH", R.drawable.camo_urban_tiger);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO8RU", R.drawable.camo_yeger);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO8US", R.drawable.camo_erdl);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO_DEFAULT", R.drawable.camo_default);
//            put("WARSAW_ID_P_CAMO_NAME_CAMO_VETERAN", R.drawable.camo_splinter);
            put("WARSAW_ID_P_CAMO_NAME_CRIMSON_WOODLAND", R.drawable.camo_crimson_woodland);
            put("WARSAW_ID_P_CAMO_NAME_DEFAULT", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_DOT_ADAPTIVE", R.drawable.camo_dot_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_DOT_AUTUMN", R.drawable.camo_dot_autumn);
            put("WARSAW_ID_P_CAMO_NAME_DOT_DESERT", R.drawable.camo_dot_desert);
            put("WARSAW_ID_P_CAMO_NAME_DOT_NAVAL", R.drawable.camo_dot_naval);
            put("WARSAW_ID_P_CAMO_NAME_DOT_SNOW", R.drawable.camo_dot_snow);
            put("WARSAW_ID_P_CAMO_NAME_DOT_URBAN", R.drawable.camo_dot_urban);
            put("WARSAW_ID_P_CAMO_NAME_DOT_WOODLAND", R.drawable.camo_dot_woodland);
            put("WARSAW_ID_P_CAMO_NAME_DUCKWEED", R.drawable.camo_duckweed);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_ADAPTIVE", R.drawable.camo_erdl_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_AUTUMN", R.drawable.camo_erdl_autumn);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_DESERT", R.drawable.camo_erdl_desert);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_NAVAL", R.drawable.camo_erdl_naval);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_SNOW", R.drawable.camo_erdl_snow);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_URBAN", R.drawable.camo_erdl_urban);
            put("WARSAW_ID_P_CAMO_NAME_ERDL_WOODLAND", R.drawable.camo_erdl_woodland);
            put("WARSAW_ID_P_CAMO_NAME_FLANKER", R.drawable.camo_flanker);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_ADAPTIVE", R.drawable.camo_flat_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_AUTUMN", R.drawable.camo_flat_autumn);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_DESERT", R.drawable.camo_flat_desert);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_NAVAL", R.drawable.camo_flat_naval);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_SNOW", R.drawable.camo_flat_snow);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_URBAN", R.drawable.camo_flat_urban);
            put("WARSAW_ID_P_CAMO_NAME_FLAT_WOODLAND", R.drawable.camo_flat_woodland);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_ADAPTIVE", R.drawable.camo_flecktarn_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_AUTUMN", R.drawable.camo_flecktarn_autumn);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_DESERT", R.drawable.camo_flecktarn_desert);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_NAVAL", R.drawable.camo_flecktarn_naval);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_SNOW", R.drawable.camo_flecktarn_snow);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_URBAN", R.drawable.camo_flecktarn_urban);
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_WOODLAND", R.drawable.camo_flecktarn_woodland);
            put("WARSAW_ID_P_CAMO_NAME_GREEN_UNDERBRUSH", R.drawable.camo_green_underbrush);
//            put("WARSAW_ID_P_CAMO_NAME_HAVOC", R.drawable.camo_havoc);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_ADAPTIVE", R.drawable.camo_hexagon_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_AUTUMN", R.drawable.camo_hexagon_autumn);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_DESERT", R.drawable.camo_hexagon_desert);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_NAVAL", R.drawable.camo_hexagon_naval);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_SNOW", R.drawable.camo_hexagon_snow);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_URBAN", R.drawable.camo_hexagon_urban);
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_WOODLAND", R.drawable.camo_hexagon_woodland);
            put("WARSAW_ID_P_CAMO_NAME_INK_BLOTCH", R.drawable.camo_ink_blotch);
            put("WARSAW_ID_P_CAMO_NAME_KLMK", R.drawable.camo_klmk);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE2", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE3", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN2", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_DICE", R.drawable.camo_dice);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY2", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN2", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN2", R.drawable.camo_default);
            put("WARSAW_ID_P_CAMO_NAME_REED_ADAPTIVE", R.drawable.camo_reed_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_REED_AUTUMN", R.drawable.camo_reed_autumn);
            put("WARSAW_ID_P_CAMO_NAME_REED_DESERT", R.drawable.camo_reed_desert);
            put("WARSAW_ID_P_CAMO_NAME_REED_NAVAL", R.drawable.camo_reed_naval);
            put("WARSAW_ID_P_CAMO_NAME_REED_SNOW", R.drawable.camo_reed_snow);
            put("WARSAW_ID_P_CAMO_NAME_REED_URBAN", R.drawable.camo_reed_urban);
            put("WARSAW_ID_P_CAMO_NAME_REED_WOODLAND", R.drawable.camo_reed_woodland);
            put("WARSAW_ID_P_CAMO_NAME_RELISH_TEMPERATE", R.drawable.camo_relish);
            put("WARSAW_ID_P_CAMO_NAME_RIPPLE", R.drawable.camo_ripple);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_ADAPTIVE", R.drawable.camo_splinter_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_AUTUMN", R.drawable.camo_splinter_autumn);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_DESERT", R.drawable.camo_splinter_desert);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_NAVAL", R.drawable.camo_splinter_naval);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_SNOW", R.drawable.camo_splinter_snow);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_URBAN", R.drawable.camo_splinter_urban);
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_WOODLAND", R.drawable.camo_splinter_woodland);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_ADAPTIVE", R.drawable.camo_spray_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_AUTUMN", R.drawable.camo_spray_autumn);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_DESERT", R.drawable.camo_spray_desert);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_NAVAL", R.drawable.camo_spray_naval);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_SNOW", R.drawable.camo_spray_snow);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_URBAN", R.drawable.camo_spray_urban);
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_WOODLAND", R.drawable.camo_spray_woodland);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_ADAPTIVE", R.drawable.camo_starburst_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_AUTUMN", R.drawable.camo_starburst_autumn);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_DESERT", R.drawable.camo_starburst_desert);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_NAVAL", R.drawable.camo_starburst_naval);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_SNOW", R.drawable.camo_starburst_snow);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_URBAN", R.drawable.camo_starburst_urban);
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_WOODLAND", R.drawable.camo_starburst_woodland);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_ADAPTIVE", R.drawable.camo_tiger_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_AUTUMN", R.drawable.camo_tiger_autumn);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_DESERT", R.drawable.camo_tiger_desert);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_NAVAL", R.drawable.camo_tiger_naval);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_SNOW", R.drawable.camo_tiger_snow);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_URBAN", R.drawable.camo_tiger_urban);
            put("WARSAW_ID_P_CAMO_NAME_TIGER_WOODLAND", R.drawable.camo_tiger_woodland);
            put("WARSAW_ID_P_CAMO_NAME_TTSKO_BLUE", R.drawable.camo_ttsko_blue);
            put("WARSAW_ID_P_CAMO_NAME_WORM_ADAPTIVE", R.drawable.camo_worm_adaptive);
            put("WARSAW_ID_P_CAMO_NAME_WORM_AUTUMN", R.drawable.camo_worm_autumn);
            put("WARSAW_ID_P_CAMO_NAME_WORM_DESERT", R.drawable.camo_worm_desert);
            put("WARSAW_ID_P_CAMO_NAME_WORM_NAVAL", R.drawable.camo_worm_naval);
            put("WARSAW_ID_P_CAMO_NAME_WORM_SNOW", R.drawable.camo_worm_snow);
            put("WARSAW_ID_P_CAMO_NAME_WORM_URBAN", R.drawable.camo_worm_urban);
            put("WARSAW_ID_P_CAMO_NAME_WORM_WOODLAND", R.drawable.camo_worm_woodland);

            // XP0
            put("WARSAW_ID_P_XP0_CAMO_NAME_DPM6", R.drawable.camo_splinter_adaptive);
            put("WARSAW_ID_P_XP0_CAMO_NAME_FIRESTARTER", R.drawable.xp0_camo_firestarter);
            put("WARSAW_ID_P_XP0_CAMO_NAME_FIRESTARTER1", R.drawable.xp0_camo_firestarter);
            put("WARSAW_ID_P_XP0_CAMO_NAME_FIRESTARTER2", R.drawable.xp0_camo_firestarter2);
            put("WARSAW_ID_P_XP0_CAMO_NAME_FIRESTARTER3", R.drawable.xp0_camo_firestarter3);

            // XP2
            put("WARSAW_ID_P_XP2_CAMO_NAME_PHANTOM", R.drawable.camo_snakeskin);
        }
    };

    public static int get(final String key) {
        return map.containsKey(key)? map.get(key) : R.drawable.acc_none;
    }
}
