package com.ninetwozero.bf4intel.base.resource.maps;

import java.util.HashMap;
import java.util.Map;

public class RankStringMap {
    private static final Map<String, String> map = new HashMap<String, String>() {
        {
            put("WARSAW_ID_P_RANK00_NAME", "RECRUIT");
            put("WARSAW_ID_P_RANK01_NAME", "Private First Class");
            put("WARSAW_ID_P_RANK02_NAME", "Private First Class II");
            put("WARSAW_ID_P_RANK03_NAME", "Private First Class III");
            put("WARSAW_ID_P_RANK04_NAME", "Private First Class IV");
            put("WARSAW_ID_P_RANK05_NAME", "Private First Class V");
            put("WARSAW_ID_P_RANK06_NAME", "Lance Corporal");
            put("WARSAW_ID_P_RANK07_NAME", "Lance Corporal II");
            put("WARSAW_ID_P_RANK08_NAME", "Lance Corporal III");
            put("WARSAW_ID_P_RANK09_NAME", "Lance Corporal IV");
            put("WARSAW_ID_P_RANK100_NAME", "Colonel");
            put("WARSAW_ID_P_RANK10_NAME", "Lance Corporal V");
            put("WARSAW_ID_P_RANK11_NAME", "Corporal");
            put("WARSAW_ID_P_RANK12_NAME", "Corporal II");
            put("WARSAW_ID_P_RANK13_NAME", "Corporal III");
            put("WARSAW_ID_P_RANK14_NAME", "Corporal IV");
            put("WARSAW_ID_P_RANK15_NAME", "Corporal V");
            put("WARSAW_ID_P_RANK16_NAME", "Sergeant");
            put("WARSAW_ID_P_RANK17_NAME", "Sergeant II");
            put("WARSAW_ID_P_RANK18_NAME", "Sergeant III");
            put("WARSAW_ID_P_RANK19_NAME", "Sergeant IV");
            put("WARSAW_ID_P_RANK20_NAME", "Sergeant V");
            put("WARSAW_ID_P_RANK21_NAME", "Staff Sergeant");
            put("WARSAW_ID_P_RANK22_NAME", "Staff Sergeant II");
            put("WARSAW_ID_P_RANK23_NAME", "Staff Sergeant III");
            put("WARSAW_ID_P_RANK24_NAME", "Staff Sergeant IV");
            put("WARSAW_ID_P_RANK25_NAME", "Staff Sergeant V");
            put("WARSAW_ID_P_RANK26_NAME", "Gunnery Sergeant");
            put("WARSAW_ID_P_RANK27_NAME", "Gunnery Sergeant II");
            put("WARSAW_ID_P_RANK28_NAME", "Gunnery Sergeant III");
            put("WARSAW_ID_P_RANK29_NAME", "Gunnery Sergeant IV");
            put("WARSAW_ID_P_RANK30_NAME", "Gunnery Sergeant V");
            put("WARSAW_ID_P_RANK31_NAME", "Master Sergeant");
            put("WARSAW_ID_P_RANK32_NAME", "Master Sergeant II");
            put("WARSAW_ID_P_RANK33_NAME", "Master Sergeant III");
            put("WARSAW_ID_P_RANK34_NAME", "Master Sergeant IV");
            put("WARSAW_ID_P_RANK35_NAME", "Master Sergeant V");
            put("WARSAW_ID_P_RANK36_NAME", "First Sergeant");
            put("WARSAW_ID_P_RANK37_NAME", "First Sergeant II");
            put("WARSAW_ID_P_RANK38_NAME", "First Sergeant III");
            put("WARSAW_ID_P_RANK39_NAME", "First Sergeant IV");
            put("WARSAW_ID_P_RANK40_NAME", "First Sergeant V");
            put("WARSAW_ID_P_RANK41_NAME", "Master Gunnery Sergeant");
            put("WARSAW_ID_P_RANK42_NAME", "Master Gunnery Sergeant II");
            put("WARSAW_ID_P_RANK43_NAME", "Master Gunnery Sergeant III");
            put("WARSAW_ID_P_RANK44_NAME", "Master Gunnery Sergeant IV");
            put("WARSAW_ID_P_RANK45_NAME", "Master Gunnery Sergeant V");
            put("WARSAW_ID_P_RANK46_NAME", "Sergeant Major");
            put("WARSAW_ID_P_RANK47_NAME", "Sergeant Major II");
            put("WARSAW_ID_P_RANK48_NAME", "Sergeant Major III");
            put("WARSAW_ID_P_RANK49_NAME", "Sergeant Major IV");
            put("WARSAW_ID_P_RANK50_NAME", "Sergeant Major V");
            put("WARSAW_ID_P_RANK51_NAME", "Warrant Officer One");
            put("WARSAW_ID_P_RANK52_NAME", "Warrant Officer One II");
            put("WARSAW_ID_P_RANK53_NAME", "Warrant Officer One III");
            put("WARSAW_ID_P_RANK54_NAME", "Warrant Officer One IV");
            put("WARSAW_ID_P_RANK55_NAME", "Warrant Officer One V");
            put("WARSAW_ID_P_RANK56_NAME", "Chief Warrant Officer Two");
            put("WARSAW_ID_P_RANK57_NAME", "Chief Warrant Officer Two II");
            put("WARSAW_ID_P_RANK58_NAME", "Chief Warrant Officer Two III");
            put("WARSAW_ID_P_RANK59_NAME", "Chief Warrant Officer Two IV");
            put("WARSAW_ID_P_RANK60_NAME", "Chief Warrant Officer Two V");
            put("WARSAW_ID_P_RANK61_NAME", "Chief Warrant Officer Three");
            put("WARSAW_ID_P_RANK62_NAME", "Chief Warrant Officer Three II");
            put("WARSAW_ID_P_RANK63_NAME", "Chief Warrant Officer Three III");
            put("WARSAW_ID_P_RANK64_NAME", "Chief Warrant Officer Three IV");
            put("WARSAW_ID_P_RANK65_NAME", "Chief Warrant Officer Three V");
            put("WARSAW_ID_P_RANK66_NAME", "Chief Warrant Officer Four");
            put("WARSAW_ID_P_RANK67_NAME", "Chief Warrant Officer Four II");
            put("WARSAW_ID_P_RANK68_NAME", "Chief Warrant Officer Four III");
            put("WARSAW_ID_P_RANK69_NAME", "Chief Warrant Officer Four IV");
            put("WARSAW_ID_P_RANK70_NAME", "Chief Warrant Officer Four V");
            put("WARSAW_ID_P_RANK71_NAME", "Chief Warrant Officer Five");
            put("WARSAW_ID_P_RANK72_NAME", "Chief Warrant Officer Five II");
            put("WARSAW_ID_P_RANK73_NAME", "Chief Warrant Officer Five III");
            put("WARSAW_ID_P_RANK74_NAME", "Chief Warrant Officer Five IV");
            put("WARSAW_ID_P_RANK75_NAME", "Chief Warrant Officer Five V");
            put("WARSAW_ID_P_RANK76_NAME", "Second Lieutenant");
            put("WARSAW_ID_P_RANK77_NAME", "Second Lieutenant II");
            put("WARSAW_ID_P_RANK78_NAME", "Second Lieutenant III");
            put("WARSAW_ID_P_RANK79_NAME", "Second Lieutenant IV");
            put("WARSAW_ID_P_RANK80_NAME", "Second Lieutenant V");
            put("WARSAW_ID_P_RANK81_NAME", "First Lieutenant");
            put("WARSAW_ID_P_RANK82_NAME", "First Lieutenant II");
            put("WARSAW_ID_P_RANK83_NAME", "First Lieutenant III");
            put("WARSAW_ID_P_RANK84_NAME", "First Lieutenant IV");
            put("WARSAW_ID_P_RANK85_NAME", "First Lieutenant V");
            put("WARSAW_ID_P_RANK86_NAME", "Captain");
            put("WARSAW_ID_P_RANK87_NAME", "Captain II");
            put("WARSAW_ID_P_RANK88_NAME", "Captain III");
            put("WARSAW_ID_P_RANK89_NAME", "Captain IV");
            put("WARSAW_ID_P_RANK90_NAME", "Captain V");
            put("WARSAW_ID_P_RANK91_NAME", "Major");
            put("WARSAW_ID_P_RANK92_NAME", "Major II");
            put("WARSAW_ID_P_RANK93_NAME", "Major III");
            put("WARSAW_ID_P_RANK94_NAME", "Major IV");
            put("WARSAW_ID_P_RANK95_NAME", "Major V");
            put("WARSAW_ID_P_RANK96_NAME", "Lieutenant Colonel");
            put("WARSAW_ID_P_RANK97_NAME", "Lieutenant Colonel II");
            put("WARSAW_ID_P_RANK98_NAME", "Lieutenant Colonel III");
            put("WARSAW_ID_P_RANK99_NAME", "Lieutenant Colonel IV");
        }
    };

    public static String get(final String key) {
        return map.containsKey(key)? map.get(key) : key;
    }
}