package com.ninetwozero.bf4intel.resource.maps;

import java.util.HashMap;
import java.util.Map;

/* Contains both WNAME and INAME */

public class WeaponStringMap {
    private static final Map<String, String> map = new HashMap<String, String>() {
        {
            put("WARSAW_ID_P_WNAME_870", "870 MCS");
            put("WARSAW_ID_P_WNAME_93R", "93R");
            put("WARSAW_ID_P_WNAME_A91", "A-91");
            put("WARSAW_ID_P_WNAME_ACR", "ACW-R");
            put("WARSAW_ID_P_WNAME_AEK971", "AEK-971");
            put("WARSAW_ID_P_WNAME_AK12", "AK-12");
            put("WARSAW_ID_P_WNAME_AK5C", "AK 5C");
            put("WARSAW_ID_P_WNAME_AKU12", "AKU-12");
            put("WARSAW_ID_P_WNAME_AMR2", "AMR-2");
            put("WARSAW_ID_P_WNAME_AMR2CQB", "AMR-2 CQB");
            put("WARSAW_ID_P_WNAME_AMR2MID", "AMR-2 MID");
            put("WARSAW_ID_P_WNAME_CBJMS", "CBJ-MS");
            put("WARSAW_ID_P_WNAME_CSLR4", "CS-LR4");
            put("WARSAW_ID_P_WNAME_CZ75", "CZ-75");
            put("WARSAW_ID_P_WNAME_CZ805", "CZ-805");
            put("WARSAW_ID_P_WNAME_DBV12", "DBV-12");
            put("WARSAW_ID_P_WNAME_FAMAS", "FAMAS");
            put("WARSAW_ID_P_WNAME_FN57", "FN57");
            put("WARSAW_ID_P_WNAME_FYJS", "FY-JS");
            put("WARSAW_ID_P_WNAME_G36C", "G36C");
            put("WARSAW_ID_P_WNAME_GALIL21", "ACE 21 CQB");
            put("WARSAW_ID_P_WNAME_GALIL23", "ACE 23");
            put("WARSAW_ID_P_WNAME_GALIL52", "ACE 52 CQB");
            put("WARSAW_ID_P_WNAME_GALIL53", "ACE 53 SV");
            put("WARSAW_ID_P_WNAME_GLOCK18", "G18");
            put("WARSAW_ID_P_WNAME_HAWK", "HAWK 12G");
            put("WARSAW_ID_P_WNAME_HK45C", "COMPACT 45");
            put("WARSAW_ID_P_WNAME_JNG90", "JNG-90");
            put("WARSAW_ID_P_WNAME_JS2", "JS2");
            put("WARSAW_ID_P_WNAME_LSAT", "LSAT");
            put("WARSAW_ID_P_WNAME_M1014", "M1014");
            put("WARSAW_ID_P_WNAME_M16A4", "M16A4");
            put("WARSAW_ID_P_WNAME_M1911", "M1911");
            put("WARSAW_ID_P_WNAME_M200", "SRR-61");
            put("WARSAW_ID_P_WNAME_M240", "M240B");
            put("WARSAW_ID_P_WNAME_M249", "M249");
            put("WARSAW_ID_P_WNAME_M39", "M39 EMR");
            put("WARSAW_ID_P_WNAME_M40A5", "M40A5");
            put("WARSAW_ID_P_WNAME_M412REX", "M412 REX");
            put("WARSAW_ID_P_WNAME_M416", "M416");
            put("WARSAW_ID_P_WNAME_M4A1", "M4");
            put("WARSAW_ID_P_WNAME_M82A3", "M82A3");
            put("WARSAW_ID_P_WNAME_M82A3CQB", "M82A3 CQB");
            put("WARSAW_ID_P_WNAME_M82A3MID", "M82A3 MID");
            put("WARSAW_ID_P_WNAME_M9", "M9");
            put("WARSAW_ID_P_WNAME_M98B", "M98B");
            put("WARSAW_ID_P_WNAME_MG4", "MG4");
            put("WARSAW_ID_P_WNAME_MK11", "MK11 MOD 0");
            put("WARSAW_ID_P_WNAME_MP443", "MP443");
            put("WARSAW_ID_P_WNAME_MX4", "MX4");
            put("WARSAW_ID_P_WNAME_P226", "P226");
            put("WARSAW_ID_P_WNAME_P90", "P90");
            put("WARSAW_ID_P_WNAME_PDR", "PDW-R");
            put("WARSAW_ID_P_WNAME_PECHENEG", "PKP PECHENEG");
            put("WARSAW_ID_P_WNAME_PP2000", "PP-2000");
            put("WARSAW_ID_P_WNAME_QBB95", "QBB-95-1");
            put("WARSAW_ID_P_WNAME_QBS09", "QBS-09");
            put("WARSAW_ID_P_WNAME_QBU88", "QBU-88");
            put("WARSAW_ID_P_WNAME_QBZ951", "QBZ-95-1");
            put("WARSAW_ID_P_WNAME_QSZ92", "QSZ-92");
            put("WARSAW_ID_P_WNAME_RFBTARGET", "RFB");
            put("WARSAW_ID_P_WNAME_RPK12", "RPK-12");
            put("WARSAW_ID_P_WNAME_SAIGA12", "SAIGA 12K");
            put("WARSAW_ID_P_WNAME_SAR21", "SAR-21");
            put("WARSAW_ID_P_WNAME_SCARH", "SCAR-H");
            put("WARSAW_ID_P_WNAME_SCARHSV", "SCAR-H SV");
            put("WARSAW_ID_P_WNAME_SCORP", "CZ-3A1");
            put("WARSAW_ID_P_WNAME_SCOUTELIT", "SCOUT ELITE");
            put("WARSAW_ID_P_WNAME_SG553", "SG553");
            put("WARSAW_ID_P_WNAME_SHORTY", "SHORTY 12G");
            put("WARSAW_ID_P_WNAME_SKS", "SKS");
            put("WARSAW_ID_P_WNAME_SPAS12", "SPAS-12");
            put("WARSAW_ID_P_WNAME_SRS", "338-RECON");
            put("WARSAW_ID_P_WNAME_STEYRAUG", "AUG A3");
            put("WARSAW_ID_P_WNAME_SV98", "SV-98");
            put("WARSAW_ID_P_WNAME_SVD12", "SVD-12");
            put("WARSAW_ID_P_WNAME_TAURUS44", ".44 MAGNUM");
            put("WARSAW_ID_P_WNAME_TYPE88", "TYPE 88 LMG");
            put("WARSAW_ID_P_WNAME_TYPE95B1", "TYPE-95B-1");
            put("WARSAW_ID_P_WNAME_ULTIM", "U-100 MK5");
            put("WARSAW_ID_P_WNAME_UMP45", "UMP-45");
            put("WARSAW_ID_P_WNAME_UMP9", "UMP-9");
            put("WARSAW_ID_P_WNAME_USAS12", "USAS-12");
            put("WARSAW_ID_P_WNAME_UTAS", "UTS 15");
            put("WARSAW_ID_P_INAME_40MM", "M320 HE");
            put("WARSAW_ID_P_INAME_40MM_FLASH", "M320 FB");
            put("WARSAW_ID_P_INAME_40MM_LVG", "M320 LVG");
            put("WARSAW_ID_P_INAME_40MM_SHG", "M320 DART");
            put("WARSAW_ID_P_INAME_40MM_SMK", "M320 SMK");
            put("WARSAW_ID_P_INAME_ACB90", "ACB-90");
            put("WARSAW_ID_P_INAME_AMMO", "AMMO BOX");
            put("WARSAW_ID_P_INAME_AMMO_PACK", "AMMO PACK");
            put("WARSAW_ID_P_INAME_ANTITANK", "ANTI-TANK");
            put("WARSAW_ID_P_INAME_BAYONETT", "BAYONET");
            put("WARSAW_ID_P_INAME_BEACON", "RADIO BEACON");
            put("WARSAW_ID_P_INAME_BPKNIFE2", "SCOUT");
            put("WARSAW_ID_P_INAME_BPKNIFE3", "TRENCH");
            put("WARSAW_ID_P_INAME_BPKNIFE4", "CARBON FIBER");
            put("WARSAW_ID_P_INAME_BPKNIFE5", "SURVIVAL");
            put("WARSAW_ID_P_INAME_BPKNIFE6", "BOWIE");
            put("WARSAW_ID_P_INAME_C4", "C4 EXPLOSIVE");
            put("WARSAW_ID_P_INAME_CARBINES", "CARBINE");
            put("WARSAW_ID_P_INAME_CLAYMORE", "M18 CLAYMORE");
            put("WARSAW_ID_P_INAME_COMBATMEDIC", "COMBAT MEDIC");
            put("WARSAW_ID_P_INAME_DEFIB", "DEFIBRILLATOR");
            put("WARSAW_ID_P_INAME_DMRS", "DMR");
            put("WARSAW_ID_P_INAME_EOD", "EOD BOT");
            put("WARSAW_ID_P_INAME_FGM148", "FGM-148 JAVELIN");
            put("WARSAW_ID_P_INAME_FIM92", "FIM-92 STINGER");
            put("WARSAW_ID_P_INAME_FIRST_AID_PACK", "FIRST AID PACK");
            put("WARSAW_ID_P_INAME_FLARE", "HAND FLARE");
            put("WARSAW_ID_P_INAME_FLASHBANG", "M84 FLASHBANG");
            put("WARSAW_ID_P_INAME_GRENADIER", "GRENADIER");
            put("WARSAW_ID_P_INAME_IGLA", "SA-18 IGLA");
            put("WARSAW_ID_P_INAME_IMPACT", "RGO IMPACT");
            put("WARSAW_ID_P_INAME_INDIRECTFIRE", "INDIRECT FIRE");
            put("WARSAW_ID_P_INAME_M136", "M136 CS");
            put("WARSAW_ID_P_INAME_M15", "M15 AT MINE");
            put("WARSAW_ID_P_INAME_M18", "M18 SMOKE");
            put("WARSAW_ID_P_INAME_M2", "M2 SLAM");
            put("WARSAW_ID_P_INAME_M26_FLECHETTE", "M26 DART");
            put("WARSAW_ID_P_INAME_M26_FRAG", "M26 FRAG");
            put("WARSAW_ID_P_INAME_M26_MASS", "M26 MASS");
            put("WARSAW_ID_P_INAME_M26_SLUG", "M26 SLUG");
            put("WARSAW_ID_P_INAME_M32MGL", "M32 MGL");
            put("WARSAW_ID_P_INAME_M34", "M34 INCENDIARY");
            put("WARSAW_ID_P_INAME_M67", "M67 FRAG");
            put("WARSAW_ID_P_INAME_MACHETE", "MACHETE");
            put("WARSAW_ID_P_INAME_MAV", "MAV");
            put("WARSAW_ID_P_INAME_MBTLAW", "MBT LAW");
            put("WARSAW_ID_P_INAME_MECHANIC", "MECHANIC");
            put("WARSAW_ID_P_INAME_MEDICBAG", "MEDIC BAG");
            put("WARSAW_ID_P_INAME_MORTAR", "M224 MORTAR");
            put("WARSAW_ID_P_INAME_MOTION_SENSOR", "MOTION SENSOR");
            put("WARSAW_ID_P_INAME_MPAPS", "MP-APS");
            put("WARSAW_ID_P_INAME_NOGADGET1", "NO GADGET");
            put("WARSAW_ID_P_INAME_NOGADGET2", "NO GADGET");
            put("WARSAW_ID_P_INAME_PERIMETERDEFENSE", "PERIMETER DEFENSE");
            put("WARSAW_ID_P_INAME_PLD", "PLD");
            put("WARSAW_ID_P_INAME_REPAIR", "REPAIR TOOL");
            put("WARSAW_ID_P_INAME_RPG7", "RPG-7V2");
            put("WARSAW_ID_P_INAME_SHADOW", "SHADOW");
            put("WARSAW_ID_P_INAME_SHANK", "SHANK");
            put("WARSAW_ID_P_INAME_SHAREDDEFENSIVE", "DEFENSIVE");
            put("WARSAW_ID_P_INAME_SHAREDOFFENSIVE", "OFFENSIVE");
            put("WARSAW_ID_P_INAME_SHOTGUNS", "SHOTGUN");
            put("WARSAW_ID_P_INAME_SMAW", "MK153 SMAW");
            put("WARSAW_ID_P_INAME_SNIPER", "SNIPER");
            put("WARSAW_ID_P_INAME_SOFLAM", "SOFLAM");
            put("WARSAW_ID_P_INAME_SPECOPS", "SPEC OPS");
            put("WARSAW_ID_P_INAME_SRAW", "FGM-172 SRAW");
            put("WARSAW_ID_P_INAME_STARSTREAK", "HVM-II");
            put("WARSAW_ID_P_INAME_UGS", "T-UGS");
            put("WARSAW_ID_P_INAME_V40", "V40 MINI");
            put("WARSAW_ID_P_INAME_XM25", "XM25 AIRBURST");
            put("WARSAW_ID_P_INAME_XM25_FLECHETTE", "XM25 DART");
            put("WARSAW_ID_P_INAME_XM25_SMK", "XM25 SMOKE");
        }
    };

    public static String get(final String key) {
        return map.containsKey(key)? map.get(key) : key;
    }
}