package com.ninetwozero.bf4intel.resources.maps.unlocks;

import com.ninetwozero.bf4intel.R;

import java.util.HashMap;
import java.util.Map;

public class VehicleUnlockImageMap {
    private static Map<String, Integer> map = new HashMap<String, Integer>() {
        {
            put("ID_P_VUNAME_SHSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_SHAA", R.drawable.vuname_heatseekers);
            put("ID_P_VUNAME_SHFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_SHAC", R.drawable.vuname_25mm_cannons);
            put("ID_P_VUNAME_SHWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_SHPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_SHECM", R.drawable.vuname_ecm_jammer);
            put("ID_P_VUNAME_SHARADAR", R.drawable.vuname_air_radar);
            put("ID_P_VUNAME_SHHELL", R.drawable.vuname_laser_guided);
            put("ID_P_VUNAME_ATKJETSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_ATKJETHEATSEEKING", R.drawable.vuname_heatseekers);
            put("ID_P_VUNAME_ATKJETPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_ATKJETROCKET", R.drawable.vuname_hydra_rockets);
            put("ID_P_VUNAME_ATKJETCECM", R.drawable.vuname_ecm_jammer);
            put("ID_P_VUNAME_ATKJETFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_ATKJETTVGUIDED", R.drawable.vuname_tv_guided_missile);
            put("ID_P_VUNAME_ATKJETWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_ATKJETJDAM", R.drawable.vuname_jdam_bomb);
            put("ID_P_VUNAME_FACTHERMAL", R.drawable.vuname_thermal_camo);
            put("ID_P_VUNAME_FACAA", R.drawable.vuname_passive_radar);
            put("ID_P_VUNAME_FACSMOKE", R.drawable.vuname_smokescreen);
            put("ID_P_VUNAME_FACPROXIMITY", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_FACIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_FACHEAT", R.drawable.vuname_30mm_cannon);
            put("ID_P_VUNAME_FACAUTOLOADER", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_FACLGMISSILE", R.drawable.vuname_laser_guided);
            put("ID_P_VUNAME_FACARADAR", R.drawable.vuname_air_radar);
            put("ID_P_VUNAME_FACAIRBURST", R.drawable.vuname_zuni_rockets);
            put("ID_P_VUNAME_FACFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_FACBURST", R.drawable.vuname_burst_cannon);
            put("ID_P_VUNAME_FACENVG", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_FACTVGUIDED", R.drawable.vuname_tv_guided_missile);
            put("ID_P_VUNAME_FACIRONFIST", R.drawable.vuname_active_protection);
            put("ID_P_VUNAME_IFVSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_IFVAT", R.drawable.vuname_tow_missile);
            put("ID_P_VUNAME_IFVGUNNERPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_IFVIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_IFVAPFSDS", R.drawable.vuname_apfsdst_shell);
            put("ID_P_VUNAME_IFVSMOKE", R.drawable.vuname_smokescreen);
            put("ID_P_VUNAME_MBTGUNNERIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_IFVWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_IFVENVG", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_IFVGUNNERSOFLAM", R.drawable.vuname_gunner_soflam);
            put("ID_P_VUNAME_IFVFLECHETTE", R.drawable.vuname_canister_shell);
            put("ID_P_VUNAME_IFVFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_IFVARMOR", R.drawable.vuname_reactive_armor);
            put("ID_P_VUNAME_IFVGUNNERFLIR", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_IFVAIRBURST", R.drawable.vuname_zuni_rockets);
            put("ID_P_VUNAME_IFVGUNNERWPSMOKE", R.drawable.vuname_gunner_incendiary);
            put("ID_P_VUNAME_IFVAIRBIRST", R.drawable.vuname_active_protection);
            put("ID_P_VUNAME_JETWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_JETGUIDEDHOMING", R.drawable.vuname_passive_radar);
            put("ID_P_VUNAME_JETPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_JET25MMCANNON", R.drawable.vuname_25mm_cannons);
            put("ID_P_VUNAME_JETECM", R.drawable.vuname_ecm_jammer);
            put("ID_P_VUNAME_JETMAVER", R.drawable.vuname_laser_guided_jet);
            put("ID_P_VUNAME_JETFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_JET30MMCANNON", R.drawable.vuname_30mm_cannon);
            put("ID_P_VUNAME_JETSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_JETAR", R.drawable.vuname_passive_radar);
            put("ID_P_VUNAME_AHSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_AHPROXGUN", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_AHFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_AHIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_AHZUNI", R.drawable.vuname_zuni_rockets);
            put("ID_P_VUNAME_AHECM", R.drawable.vuname_ecm_jammer);
            put("ID_P_VUNAME_AHGHELL", R.drawable.vuname_laser_guided);
            put("ID_P_VUNAME_AHARADAR", R.drawable.vuname_air_radar);
            put("ID_P_VUNAME_AHENVG", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_AHTOW", R.drawable.vuname_tow_missile);
            put("ID_P_VUNAME_AHTVG", R.drawable.vuname_tv_guided_missile);
            put("ID_P_VUNAME_AHGUIDE", R.drawable.vuname_smart_rockets);
            put("ID_P_VUNAME_MBTSTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_MBTATGM", R.drawable.vuname_guided_shell);
            put("ID_P_VUNAME_MBTGUNNERPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_MBTIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_MBTHESHELL", R.drawable.vuname_he_shell);
            put("ID_P_VUNAME_MBTSMOKE", R.drawable.vuname_smokescreen);
            put("ID_P_VUNAME_MBTWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_MBTGUNNERIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_MBTHMG", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_MBTENVG", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_MBTCANISTER", R.drawable.vuname_coaxial_hmg);
            put("ID_P_VUNAME_MBTFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_MBTGUNNERSOFLAM", R.drawable.vuname_gunner_soflam);
            put("ID_P_VUNAME_MBTARMOR", R.drawable.vuname_reactive_armor);
            put("ID_P_VUNAME_MBTSTAFF", R.drawable.vuname_staff_shell);
            put("ID_P_VUNAME_MBTGUNNERFLIR", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_MBTAPFSDS", R.drawable.vuname_sabot_shell);
            put("ID_P_VUNAME_MBTGUNNERWPSMOKE", R.drawable.vuname_gunner_incendiary);
            put("ID_P_VUNAME_MBTAIRBIRST", R.drawable.vuname_active_protection);
            put("ID_P_VUNAME_AASTEALTH", R.drawable.vuname_stealth_coating);
            put("ID_P_VUNAME_AAVIRNV", R.drawable.vuname_irnv_optics);
            put("ID_P_VUNAME_AAWPNEFF", R.drawable.vuname_belt_feeder);
            put("ID_P_VUNAME_AAAA", R.drawable.vuname_passive_radar);
            put("ID_P_VUNAME_AAPROX", R.drawable.vuname_gunner_proximity_scan);
            put("ID_P_VUNAME_AASMOKE", R.drawable.vuname_smokescreen);
            put("ID_P_VUNAME_AAHS", R.drawable.vuname_30mm_cannon);
            put("ID_P_VUNAME_AAENVG", R.drawable.vuname_thermal_optics);
            put("ID_P_VUNAME_AAARMOR", R.drawable.vuname_reactive_armor);
            put("ID_P_VUNAME_AAFIREEX", R.drawable.vuname_fire_extinguisher);
            put("ID_P_VUNAME_AAVAIRBURST", R.drawable.vuname_zuni_rockets);
            put("ID_P_VUNAME_AAARADAR", R.drawable.vuname_air_radar);
            put("ID_P_VUNAME_AAVAR", R.drawable.vuname_passive_radar);
            put("ID_P_VUNAME_AAVIRONFIST", R.drawable.vuname_active_protection);
        }
    };

    public static int get(String slug) {
        return map.containsKey(slug) ? map.get(slug) : R.drawable.kit_none;
    }
}
