package com.ninetwozero.bf4intel.resources.maps;

import java.util.HashMap;
import java.util.Map;

public class CamoStringMap {
    private static final Map<String, String> map = new HashMap<String, String>() {
        {
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_ADAPTIVE", "Atomic Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_AUTUMN", "Atomic Autumn");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_DESERT", "Atomic Desert");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_NAVAL", "Atomic Naval");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_SNOW", "Atomic Snow");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_URBAN", "Atomic Urban");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_WOODLAND", "Atomic Woodland");
            put("WARSAW_ID_P_CAMO_NAME_BEO_GAM", "Beo Gam");
            put("WARSAW_ID_P_CAMO_NAME_BLACK_SHARK", "Black Shark");
            put("WARSAW_ID_P_CAMO_NAME_BLUESKY", "Blue Sky");
            put("WARSAW_ID_P_CAMO_NAME_BLUE_TIGER", "Blue Tiger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1CH", "Urban Airborne");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1RU", "Izlom");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1US", "Tricolor Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2CH", "Dense Urban");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2RU", "Berezka");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2US", "Marpat Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3CH", "Oceanic Green");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3RU", "Partizan");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3US", "Chocolate Chip");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4CH", "Pla Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4RU", "Vdv Flectar");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4US", "Vine Leaf");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5CH", "Pla Naval");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5RU", "Spetsnaz Jungle");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5US", "Ucp");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6CH", "Pla Temperate");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6RU", "Rastr");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6US", "Marpat");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7CH", "Oceanic Blue");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7RU", "Klmk");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7US", "Tiger Stripe");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8CH", "Urban Tiger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8RU", "Yeger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8US", "Erdl");
            put("WARSAW_ID_P_CAMO_NAME_CAMO_DEFAULT", "Default");
            put("WARSAW_ID_P_CAMO_NAME_CAMO_VETERAN", "Splinter");
            put("WARSAW_ID_P_CAMO_NAME_CRIMSON_WOODLAND", "Crimson Woodland");
            put("WARSAW_ID_P_CAMO_NAME_DEFAULT", "Default");
            put("WARSAW_ID_P_CAMO_NAME_DOT_ADAPTIVE", "Dot Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_DOT_AUTUMN", "Dot Autumn");
            put("WARSAW_ID_P_CAMO_NAME_DOT_DESERT", "Dot Desert");
            put("WARSAW_ID_P_CAMO_NAME_DOT_NAVAL", "Dot Naval");
            put("WARSAW_ID_P_CAMO_NAME_DOT_SNOW", "Dot Snow");
            put("WARSAW_ID_P_CAMO_NAME_DOT_URBAN", "Dot Urban");
            put("WARSAW_ID_P_CAMO_NAME_DOT_WOODLAND", "Dot Woodland");
            put("WARSAW_ID_P_CAMO_NAME_DUCKWEED", "Duckweed");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_ADAPTIVE", "Erdl Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_AUTUMN", "Erdl Autumn");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_DESERT", "Erdl Desert");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_NAVAL", "Erdl Naval");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_SNOW", "Erdl Snow");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_URBAN", "Erdl Urban");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_WOODLAND", "Erdl Woodland");
            put("WARSAW_ID_P_CAMO_NAME_FLANKER", "Flanker");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_ADAPTIVE", "Flat Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_AUTUMN", "Flat Autumn");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_DESERT", "Flat Desert");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_NAVAL", "Flat Naval");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_SNOW", "Flat Snow");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_URBAN", "Flat Urban");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_WOODLAND", "Flat Woodland");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_ADAPTIVE", "Flecktarn Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_AUTUMN", "Flecktarn Autumn");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_DESERT", "Flecktarn Desert");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_NAVAL", "Flecktarn Naval");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_SNOW", "Flecktarn Snow");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_URBAN", "Flecktarn Urban");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_WOODLAND", "Flecktarn Woodland");
            put("WARSAW_ID_P_CAMO_NAME_GREEN_UNDERBRUSH", "Green Underbrush");
            put("WARSAW_ID_P_CAMO_NAME_HAVOC", "Havoc");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_ADAPTIVE", "Hexagon Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_AUTUMN", "Hexagon Autumn");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_DESERT", "Hexagon Desert");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_NAVAL", "Hexagon Naval");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_SNOW", "Hexagon Snow");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_URBAN", "Hexagon Urban");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_WOODLAND", "Hexagon Woodland");
            put("WARSAW_ID_P_CAMO_NAME_INK_BLOTCH", "Ink Blotch");
            put("WARSAW_ID_P_CAMO_NAME_KLMK", "Klmk");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE3", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_DICE", "Dice");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_REED_ADAPTIVE", "Reed Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_REED_AUTUMN", "Reed Autumn");
            put("WARSAW_ID_P_CAMO_NAME_REED_DESERT", "Reed Desert");
            put("WARSAW_ID_P_CAMO_NAME_REED_NAVAL", "Reed Naval");
            put("WARSAW_ID_P_CAMO_NAME_REED_SNOW", "Reed Snow");
            put("WARSAW_ID_P_CAMO_NAME_REED_URBAN", "Reed Urban");
            put("WARSAW_ID_P_CAMO_NAME_REED_WOODLAND", "Reed Woodland");
            put("WARSAW_ID_P_CAMO_NAME_RELISH_TEMPERATE", "Relish");
            put("WARSAW_ID_P_CAMO_NAME_RIPPLE", "Ripple");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_ADAPTIVE", "Splinter Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_AUTUMN", "Splinter Autumn");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_DESERT", "Splinter Desert");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_NAVAL", "Splinter Naval");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_SNOW", "Splinter Snow");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_URBAN", "Splinter Urban");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_WOODLAND", "Splinter Woodland");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_ADAPTIVE", "Spray Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_AUTUMN", "Spray Autumn");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_DESERT", "Spray Desert");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_NAVAL", "Spray Naval");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_SNOW", "Spray Snow");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_URBAN", "Spray Urban");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_WOODLAND", "Spray Woodland");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_ADAPTIVE", "Starburst Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_AUTUMN", "Starburst Autumn");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_DESERT", "Starburst Desert");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_NAVAL", "Starburst Naval");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_SNOW", "Starburst Snow");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_URBAN", "Starburst Urban");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_WOODLAND", "Starburst Woodland");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_ADAPTIVE", "Tiger Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_AUTUMN", "Tiger Autumn");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_DESERT", "Tiger Desert");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_NAVAL", "Tiger Naval");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_SNOW", "Tiger Snow");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_URBAN", "Tiger Urban");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_WOODLAND", "Tiger Woodland");
            put("WARSAW_ID_P_CAMO_NAME_TTSKO_BLUE", "Ttsko Blue");
            put("WARSAW_ID_P_CAMO_NAME_WORM_ADAPTIVE", "Worm Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_WORM_AUTUMN", "Worm Autumn");
            put("WARSAW_ID_P_CAMO_NAME_WORM_DESERT", "Worm Desert");
            put("WARSAW_ID_P_CAMO_NAME_WORM_NAVAL", "Worm Naval");
            put("WARSAW_ID_P_CAMO_NAME_WORM_SNOW", "Worm Snow");
            put("WARSAW_ID_P_CAMO_NAME_WORM_URBAN", "Worm Urban");
            put("WARSAW_ID_P_CAMO_NAME_WORM_WOODLAND", "Worm Woodland");
        }
    };

    public static String get(final String key) {
        return map.containsKey(key)? map.get(key) : key;
    }
}
