package com.ninetwozero.bf4intel.resources.maps;

import java.util.HashMap;
import java.util.Map;

public class MiscBattlePackStringMap {
    private static final Map<String, String> map = new HashMap<String, String>() {
        {
            // Battle Pack Names
            put("WARSAW_ID_P_BATTLEPACK_BRONZE", "Bronze Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_BRONZE_AXE", "Axe Bronze Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_BRONZE_GEM", "Keep Fighting Bronze Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_BRONZE_PRIMA", "Prima Bronze Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_BRONZE_SLIM_JIM", "Slim Jim Bronze Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD", "Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_AXE", "Axe Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_DELUXE", "Deluxe Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_DIGITAL_DELUXE", "Origin Digital Deluxe Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_GAMESTOP", "Pre-order Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_GEM", "Vip Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_PRIMA", "Prima Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_GOLD_SLIM_JIM", "Slim Jim Gold Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_PREMIUM", "Premium Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_PROMO_VETERAN", "Veteran Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_SILVER", "Silver Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_SILVER_AXE", "Axe Silver Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_SILVER_GEM", "Welcome Back Silver Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_SILVER_SLIM_JIM", "Slim Jim Silver Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_338-RECON", "338-recon Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_44_MAGNUM", ".44 Magnum Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_870_MCS", "870 MCS Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_93R", "93R Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_A-91", "A-91 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_ACE_21_CQB", "Ace 21 CQB Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_ACE_23", "ACE 23 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_ACE_52_CQB", "ACE 52 CQB Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_ACE_53_SV", "ACE 53 SV Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_ACW-R", "ACW-r Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_AEK-971", "AEK-971 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_AK-12", "AK-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_AKU-12", "AKU-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_AK_5C", "AK 5C Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_AUG_A3", "AUG A3 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_CBJ-MS", "CBJ-SM Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_COMPACT_45", "Compact 45 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_CS-LR4", "CS-LR4 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_CZ-3A1", "CZ-3A1 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_CZ-75", "CZ-75 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_CZ-805", "CZ-805 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_DBV-12", "DBV-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_FAMAS", "Famas Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_FN57", "FN57 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_FY-JS", "FY-JS Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_G18", "G18 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_G36C", "G36C Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_HAWK_12G", "Hawk 12g Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_JNG-90", "JNG-90 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_JS2", "JS2 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_L85A2", "L85A2 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_L96A1", "L96A1 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_LSAT", "LSAT Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M1014", "M1014 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M16A3", "M16a4 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M1911", "M1911 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M240B", "M240B Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M249", "M249 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M39_EMR", "M39 EMR Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M40A5", "M40A5 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M412_REX", "M412 Rex Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M416", "M416 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M4A1", "M4 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M9", "M9 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_M98B", "M98B Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MG4", "MG4 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MK11_MOD_0", "MK11 Mod 0 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MP443", "MP443 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MP7", "MP7 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MTAT-21", "MTAR-21 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_MX4", "MX4 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_P226", "P226 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_P90", "P90 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_PDW-R", "PDW-R Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_PKP_PECHENEG", "PKP Pecheneg Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_PP-2000", "PP-2000 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_QBB-95-1", "QBB-95-1 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_QBS-09", "QBS-09 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_QBU-88", "QBU-88 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_QBZ-95-1", "QBZ-95-1 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_QSZ-92", "QSZ-92 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_RFB", "RFB Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_RPK-12", "RPK-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_RPK-74M", "RPK-74m Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SAIGA_12K", "Saiga 12k Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SAR-21", "SAR-21 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SCAR-H", "SCAR-H Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SCAR-H_SV", "SCAR-H SV Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SCOUT_ELITE", "Scout Elite Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SG553", "SG553 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SHORTY_12G", "Shorty 12g Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SKS", "SKS Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SPAS-12", "SPAS-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SRR-61", "SRR-61 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SV-98", "SV-98 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_SVD-12", "SVD-12 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_TYPE-95B-1", "Type-95B-1 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_TYPE_88_LMG", "Type 88 Lmg Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_U-100_MK5", "U-100 MK5 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_UMP-45", "UMP-45 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_UMP-9", "UMP-9 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_WEAPON_UTS_15", "UTS 15 Battlepack");
            put("WARSAW_ID_P_BATTLEPACK_XP_SLIM_JIM", "Slim Jim Double Xp Battlepack");

            // Boosts
            put("WARSAW_ID_P_ULTIMATE_25", "25% XP Boost");
            put("WARSAW_ID_P_ULTIMATE_50", "50% XP Boost");
            put("WARSAW_ID_P_ULTIMATE_100", "100% XP Boost");
            put("WARSAW_ID_P_ULTIMATE_200", "200% XP Boost");

            // CAMO
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_ADAPTIVE", "Atomic Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_AUTUMN", "Atomic Autumn");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_DESERT", "Atomic Desert");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_NAVAL", "Atomic Naval");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_SNOW", "Atomic Snow");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_URBAN", "Atomic Urban");
            put("WARSAW_ID_P_CAMO_NAME_ATOMIC_WOODLAND", "Atomic Woodland");
            put("WARSAW_ID_P_CAMO_NAME_BEO_GAM", "Beo Gam");
            put("WARSAW_ID_P_CAMO_NAME_BLACK_SHARK", "Black Shark");
            put("WARSAW_ID_P_CAMO_NAME_BLUESKY", "Blue Sky");
            put("WARSAW_ID_P_CAMO_NAME_BLUE_TIGER", "Blue Tiger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1CH", "Urban Airborne");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1RU", "Izlom");
            put("WARSAW_ID_P_CAMO_NAME_CAMO1US", "Tricolor Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2CH", "Dense Urban");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2RU", "Berezka");
            put("WARSAW_ID_P_CAMO_NAME_CAMO2US", "Marpat Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3CH", "Oceanic Green");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3RU", "Partizan");
            put("WARSAW_ID_P_CAMO_NAME_CAMO3US", "Chocolate Chip");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4CH", "Pla Desert");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4RU", "Vdv Flectar");
            put("WARSAW_ID_P_CAMO_NAME_CAMO4US", "Vine Leaf");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5CH", "Pla Naval");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5RU", "Spetsnaz Jungle");
            put("WARSAW_ID_P_CAMO_NAME_CAMO5US", "Ucp");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6CH", "Pla Temperate");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6RU", "Rastr");
            put("WARSAW_ID_P_CAMO_NAME_CAMO6US", "Marpat");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7CH", "Oceanic Blue");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7RU", "Klmk");
            put("WARSAW_ID_P_CAMO_NAME_CAMO7US", "Tiger Stripe");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8CH", "Urban Tiger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8RU", "Yeger");
            put("WARSAW_ID_P_CAMO_NAME_CAMO8US", "Erdl");
            put("WARSAW_ID_P_CAMO_NAME_CAMO_DEFAULT", "Default");
            put("WARSAW_ID_P_CAMO_NAME_CAMO_VETERAN", "Splinter");
            put("WARSAW_ID_P_CAMO_NAME_CRIMSON_WOODLAND", "Crimson Woodland");
            put("WARSAW_ID_P_CAMO_NAME_DEFAULT", "Default");
            put("WARSAW_ID_P_CAMO_NAME_DOT_ADAPTIVE", "Dot Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_DOT_AUTUMN", "Dot Autumn");
            put("WARSAW_ID_P_CAMO_NAME_DOT_DESERT", "Dot Desert");
            put("WARSAW_ID_P_CAMO_NAME_DOT_NAVAL", "Dot Naval");
            put("WARSAW_ID_P_CAMO_NAME_DOT_SNOW", "Dot Snow");
            put("WARSAW_ID_P_CAMO_NAME_DOT_URBAN", "Dot Urban");
            put("WARSAW_ID_P_CAMO_NAME_DOT_WOODLAND", "Dot Woodland");
            put("WARSAW_ID_P_CAMO_NAME_DUCKWEED", "Duckweed");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_ADAPTIVE", "Erdl Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_AUTUMN", "Erdl Autumn");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_DESERT", "Erdl Desert");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_NAVAL", "Erdl Naval");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_SNOW", "Erdl Snow");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_URBAN", "Erdl Urban");
            put("WARSAW_ID_P_CAMO_NAME_ERDL_WOODLAND", "Erdl Woodland");
            put("WARSAW_ID_P_CAMO_NAME_FLANKER", "Flanker");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_ADAPTIVE", "Flat Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_AUTUMN", "Flat Autumn");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_DESERT", "Flat Desert");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_NAVAL", "Flat Naval");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_SNOW", "Flat Snow");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_URBAN", "Flat Urban");
            put("WARSAW_ID_P_CAMO_NAME_FLAT_WOODLAND", "Flat Woodland");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_ADAPTIVE", "Flecktarn Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_AUTUMN", "Flecktarn Autumn");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_DESERT", "Flecktarn Desert");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_NAVAL", "Flecktarn Naval");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_SNOW", "Flecktarn Snow");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_URBAN", "Flecktarn Urban");
            put("WARSAW_ID_P_CAMO_NAME_FLECKTARN_WOODLAND", "Flecktarn Woodland");
            put("WARSAW_ID_P_CAMO_NAME_GREEN_UNDERBRUSH", "Green Underbrush");
            put("WARSAW_ID_P_CAMO_NAME_HAVOC", "Havoc");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_ADAPTIVE", "Hexagon Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_AUTUMN", "Hexagon Autumn");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_DESERT", "Hexagon Desert");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_NAVAL", "Hexagon Naval");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_SNOW", "Hexagon Snow");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_URBAN", "Hexagon Urban");
            put("WARSAW_ID_P_CAMO_NAME_HEXAGON_WOODLAND", "Hexagon Woodland");
            put("WARSAW_ID_P_CAMO_NAME_INK_BLOTCH", "Ink Blotch");
            put("WARSAW_ID_P_CAMO_NAME_KLMK", "Klmk");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BLUE3", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_BROWN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_DICE", "Dice");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GRAY2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_GREEN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN", "Default");
            put("WARSAW_ID_P_CAMO_NAME_NOCAMO_TAN2", "Default");
            put("WARSAW_ID_P_CAMO_NAME_REED_ADAPTIVE", "Reed Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_REED_AUTUMN", "Reed Autumn");
            put("WARSAW_ID_P_CAMO_NAME_REED_DESERT", "Reed Desert");
            put("WARSAW_ID_P_CAMO_NAME_REED_NAVAL", "Reed Naval");
            put("WARSAW_ID_P_CAMO_NAME_REED_SNOW", "Reed Snow");
            put("WARSAW_ID_P_CAMO_NAME_REED_URBAN", "Reed Urban");
            put("WARSAW_ID_P_CAMO_NAME_REED_WOODLAND", "Reed Woodland");
            put("WARSAW_ID_P_CAMO_NAME_RELISH_TEMPERATE", "Relish");
            put("WARSAW_ID_P_CAMO_NAME_RIPPLE", "Ripple");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_ADAPTIVE", "Splinter Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_AUTUMN", "Splinter Autumn");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_DESERT", "Splinter Desert");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_NAVAL", "Splinter Naval");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_SNOW", "Splinter Snow");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_URBAN", "Splinter Urban");
            put("WARSAW_ID_P_CAMO_NAME_SPLINTER_WOODLAND", "Splinter Woodland");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_ADAPTIVE", "Spray Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_AUTUMN", "Spray Autumn");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_DESERT", "Spray Desert");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_NAVAL", "Spray Naval");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_SNOW", "Spray Snow");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_URBAN", "Spray Urban");
            put("WARSAW_ID_P_CAMO_NAME_SPRAY_WOODLAND", "Spray Woodland");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_ADAPTIVE", "Starburst Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_AUTUMN", "Starburst Autumn");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_DESERT", "Starburst Desert");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_NAVAL", "Starburst Naval");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_SNOW", "Starburst Snow");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_URBAN", "Starburst Urban");
            put("WARSAW_ID_P_CAMO_NAME_STARBURST_WOODLAND", "Starburst Woodland");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_ADAPTIVE", "Tiger Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_AUTUMN", "Tiger Autumn");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_DESERT", "Tiger Desert");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_NAVAL", "Tiger Naval");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_SNOW", "Tiger Snow");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_URBAN", "Tiger Urban");
            put("WARSAW_ID_P_CAMO_NAME_TIGER_WOODLAND", "Tiger Woodland");
            put("WARSAW_ID_P_CAMO_NAME_TTSKO_BLUE", "Ttsko Blue");
            put("WARSAW_ID_P_CAMO_NAME_WORM_ADAPTIVE", "Worm Adaptive");
            put("WARSAW_ID_P_CAMO_NAME_WORM_AUTUMN", "Worm Autumn");
            put("WARSAW_ID_P_CAMO_NAME_WORM_DESERT", "Worm Desert");
            put("WARSAW_ID_P_CAMO_NAME_WORM_NAVAL", "Worm Naval");
            put("WARSAW_ID_P_CAMO_NAME_WORM_SNOW", "Worm Snow");
            put("WARSAW_ID_P_CAMO_NAME_WORM_URBAN", "Worm Urban");
            put("WARSAW_ID_P_CAMO_NAME_WORM_WOODLAND", "Worm Woodland");

            // Emblems
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_01", "Drone");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_02", "Gunship");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_03", "Stealthjet");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_04", "Binocular");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_05", "Cracket");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_06", "Crown 3");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_07", "Raptor");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_08", "T -rex");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_09", "Triceratops");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_10", "Eod Bot");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_11", "Eye");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_12", "Flames");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_13", "Gear");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_14", "Grenade");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_15", "Armored Jeep");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_16", "Fast Jeep");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_17", "Ifv");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_18", "Mobile Aa2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_19", "Ground Quad");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_20", "Headshot");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_21", "Transport Heli");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_22", "Jam");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_23", "Lightning");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_24", "Lion2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_25", "Longrange");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_26", "Mag");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_27", "Medal Frame");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_28", "Medal Ring");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_29", "Medal Ring 2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_30", "Medal Ring 3");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_31", "Medal Shape 3");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_32", "Missile");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_33", "Reduce Fall");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_34", "Shield 9");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_35", "Shield 5");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_36", "Shield 8");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_37", "Snakestick Wings");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_38", "Specialist");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_39", "Stationary Aa 2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_40", "Stationary Mg 2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_41", "Stationary Tow 2");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_42", "Suppression");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_43", "Sword");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_44", "Team Play");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_45", "Timer");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_46", "Aav");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_47", "Rhib Boat");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_48", "Dmr");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_49", "Wheel 3");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_50", "Wreath 3");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_51", "Attack Jet");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_52", "Explosion");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_53", "Fleur-de-lis");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_54", "Mlr");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_55", "Tank");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_56", "Handshake");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_57", "Attack Heli");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_58", "Hooah");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_59", "Lion");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_60", "Mine");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_61", "Square Corner");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_62", "Half Circle");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_63", "Line");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_64", "Crescent Moon");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_65", "Drop");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_66", "Bent Line");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_67", "Right Triangle");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_68", "Sale!");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_69", "Angry Fist");
            put("WARSAW_ID_M_BATTLEPACK_EMBLEM_70", "Epic Goat");
        }
    };

    public static String get(final String key) {
        return map.containsKey(key)? map.get(key) : key;
    }
}
