package com.ninetwozero.bf4intel.resources.maps;

import com.ninetwozero.bf4intel.R;

import java.util.HashMap;
import java.util.Map;

public class RankImageMap {
    private static final Map<Integer, Integer> images = new HashMap<Integer, Integer>() {
        {
            put(0, R.drawable.r0);
            put(1, R.drawable.r1);
            put(2, R.drawable.r2);
            put(3, R.drawable.r3);
            put(4, R.drawable.r4);
            put(5, R.drawable.r5);
            put(6, R.drawable.r6);
            put(7, R.drawable.r7);
            put(8, R.drawable.r8);
            put(9, R.drawable.r9);
            put(10, R.drawable.r10);
            put(11, R.drawable.r11);
            put(12, R.drawable.r12);
            put(13, R.drawable.r13);
            put(14, R.drawable.r14);
            put(15, R.drawable.r15);
            put(16, R.drawable.r16);
            put(17, R.drawable.r17);
            put(18, R.drawable.r18);
            put(19, R.drawable.r19);
            put(10, R.drawable.r10);
            put(21, R.drawable.r21);
            put(22, R.drawable.r22);
            put(23, R.drawable.r23);
            put(24, R.drawable.r24);
            put(25, R.drawable.r25);
            put(26, R.drawable.r26);
            put(27, R.drawable.r27);
            put(28, R.drawable.r28);
            put(29, R.drawable.r29);
            put(30, R.drawable.r10);
            put(31, R.drawable.r31);
            put(32, R.drawable.r32);
            put(33, R.drawable.r33);
            put(34, R.drawable.r34);
            put(35, R.drawable.r35);
            put(36, R.drawable.r36);
            put(37, R.drawable.r37);
            put(38, R.drawable.r38);
            put(39, R.drawable.r39);
            put(40, R.drawable.r40);
            put(41, R.drawable.r41);
            put(42, R.drawable.r42);
            put(43, R.drawable.r43);
            put(44, R.drawable.r44);
            put(45, R.drawable.r45);
            put(46, R.drawable.r46);
            put(47, R.drawable.r47);
            put(48, R.drawable.r48);
            put(49, R.drawable.r49);
            put(50, R.drawable.r50);
            put(51, R.drawable.r51);
            put(52, R.drawable.r52);
            put(53, R.drawable.r53);
            put(54, R.drawable.r54);
            put(55, R.drawable.r55);
            put(56, R.drawable.r56);
            put(57, R.drawable.r57);
            put(58, R.drawable.r58);
            put(59, R.drawable.r59);
            put(60, R.drawable.r60);
            put(61, R.drawable.r61);
            put(62, R.drawable.r62);
            put(63, R.drawable.r63);
            put(64, R.drawable.r64);
            put(65, R.drawable.r65);
            put(66, R.drawable.r66);
            put(67, R.drawable.r67);
            put(68, R.drawable.r68);
            put(69, R.drawable.r69);
            put(70, R.drawable.r70);
            put(71, R.drawable.r71);
            put(72, R.drawable.r72);
            put(73, R.drawable.r73);
            put(74, R.drawable.r74);
            put(75, R.drawable.r75);
            put(76, R.drawable.r76);
            put(77, R.drawable.r77);
            put(78, R.drawable.r78);
            put(79, R.drawable.r79);
            put(80, R.drawable.r80);
            put(81, R.drawable.r81);
            put(82, R.drawable.r82);
            put(83, R.drawable.r83);
            put(84, R.drawable.r84);
            put(85, R.drawable.r85);
            put(86, R.drawable.r86);
            put(87, R.drawable.r87);
            put(88, R.drawable.r88);
            put(89, R.drawable.r89);
            put(90, R.drawable.r90);
            put(91, R.drawable.r91);
            put(92, R.drawable.r92);
            put(93, R.drawable.r93);
            put(94, R.drawable.r94);
            put(95, R.drawable.r95);
            put(96, R.drawable.r96);
            put(97, R.drawable.r97);
            put(98, R.drawable.r98);
            put(99, R.drawable.r99);
            put(100, R.drawable.r100);
            put(101, R.drawable.r101);
            put(102, R.drawable.r102);
            put(103, R.drawable.r103);
            put(104, R.drawable.r104);
            put(105, R.drawable.r105);
            put(106, R.drawable.r106);
            put(107, R.drawable.r107);
            put(108, R.drawable.r108);
            put(109, R.drawable.r109);
            put(110, R.drawable.r110);
        }
    };

    public static int get(final int rank) {
        return images.containsKey(rank)? images.get(rank) : R.drawable.r0;
    }
}
